name: RealTime
author: killer549
api: 3.0.0
version: 1.2.1
main: killer549\realtime\RealTime
permissions:
  realtime.command.*:
    default: op
    children:
      realtime.command.current:
        default: true
      realtime.command.disable:
        default: op
      realtime.command.enable:
        default: op
      realtime.command.help:
        default: true
      realtime.command.reload:
        default: op
      realtime.command.status:
        default: true
